import { StyleSheet } from 'react-native';

export const COLORS = {
  bg: '#121212',
  bgSoft: '#1E1E1E',
  bgInput: '#2C2C2C',
  bgButton: '#444',
  bgButtonAlt: '#555',
  border: '#333',
  borderStrong: '#444',
  borderSoft: '#555',
  text: '#FFF',
  textDim: '#A0A0A0',
  textHint: '#777',
  blue: '#00BFFF',
  primary: '#004A99',
  green: '#28A745',
  yellow: '#FFC107',
  red: '#DC3545',
  black: '#000',
  white: '#FFF',
};

export const S = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg, padding: 20 },

  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 40, marginBottom: 20 },
  headerTitle: { color: COLORS.text, fontSize: 20, fontWeight: 'bold' },
  subHeader: { color: COLORS.textDim, fontSize: 12 },
  logoutBtn: { backgroundColor: COLORS.red, padding: 8, borderRadius: 6 },
  logoutText: { color: COLORS.text, fontSize: 12, fontWeight: 'bold' },

  sectionTitle: { color: COLORS.text, fontSize: 16, fontWeight: 'bold', marginBottom: 10 },
  textPutih: { color: COLORS.text, marginBottom: 5 },
  textPutihBold: { color: COLORS.text, fontSize: 15, fontWeight: 'bold', marginBottom: 5 },
  ketKlik: { color: COLORS.blue, fontSize: 11, fontStyle: 'italic' },
  ketKlikYellow: { color: COLORS.yellow, fontSize: 11, fontStyle: 'italic', marginTop: 5 },
  ketKlikGreen: { color: COLORS.green, fontSize: 11, fontStyle: 'italic' },

  cardForm: { backgroundColor: COLORS.bgSoft, padding: 15, borderRadius: 10, borderWidth: 1, borderColor: COLORS.border, marginBottom: 20 },
  infoNomor: { color: COLORS.blue, fontSize: 12, marginBottom: 10 },
  input: { backgroundColor: COLORS.bgInput, color: COLORS.text, height: 45, borderRadius: 8, paddingHorizontal: 12, marginBottom: 10 },

  btnUpload: { backgroundColor: COLORS.bgButton, height: 45, borderRadius: 8, justifyContent: 'center', alignItems: 'center', marginBottom: 15, borderWidth: 1, borderColor: COLORS.blue, borderStyle: 'dashed' },
  btnUploadText: { color: COLORS.blue, fontWeight: 'bold' },
  btnUploadYellow: { backgroundColor: COLORS.bgButton, height: 45, borderRadius: 8, justifyContent: 'center', alignItems: 'center', marginVertical: 10, borderWidth: 1, borderColor: COLORS.yellow, borderStyle: 'dashed' },
  btnUploadYellowText: { color: COLORS.yellow, fontWeight: 'bold' },

  submitBtn: { backgroundColor: COLORS.green, height: 45, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  submitBtnBlue: { backgroundColor: COLORS.blue, height: 45, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  submitText: { color: COLORS.text, fontWeight: 'bold' },

  suratCard: { backgroundColor: COLORS.bgSoft, padding: 15, borderRadius: 10, marginBottom: 12, borderWidth: 1, borderColor: COLORS.border },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  nomorSurat: { color: COLORS.blue, fontWeight: 'bold', fontSize: 14 },
  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  badgeText: { color: COLORS.black, fontSize: 10, fontWeight: 'bold' },

  modalBg: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: COLORS.bgSoft, borderRadius: 12, padding: 20, borderWidth: 1, borderColor: COLORS.borderStrong },
  modalContentTall: { backgroundColor: COLORS.bgSoft, borderRadius: 12, padding: 20, borderWidth: 1, borderColor: COLORS.borderStrong, maxHeight: '85%' },
  modalTitle: { color: COLORS.text, fontSize: 18, fontWeight: 'bold', marginBottom: 15, textAlign: 'center' },
  modalLabel: { color: COLORS.textDim, fontSize: 12, marginTop: 8, marginBottom: 5 },
  modalValue: { color: COLORS.text, fontSize: 15, fontWeight: '500', marginBottom: 5 },

  btnBukaFile: { backgroundColor: COLORS.bgButton, padding: 12, borderRadius: 8, borderWidth: 1, borderColor: COLORS.blue, alignItems: 'center', marginBottom: 10 },
  btnBukaFileText: { color: COLORS.blue, fontWeight: 'bold' },
  btnBukaFileBig: { backgroundColor: COLORS.bgButton, padding: 12, borderRadius: 8, borderWidth: 1, borderColor: COLORS.blue, alignItems: 'center', marginVertical: 15 },
  btnBukaFileBigText: { color: COLORS.blue, fontWeight: 'bold', fontSize: 15 },

  infoKuning: { color: COLORS.yellow, textAlign: 'center', fontWeight: 'bold', marginVertical: 10 },
  infoBiru: { color: COLORS.blue, textAlign: 'center', fontWeight: 'bold', marginVertical: 10 },
  infoHijau: { color: COLORS.green, textAlign: 'center', fontWeight: 'bold', marginVertical: 10 },

  btnClose: { backgroundColor: COLORS.bgButton, padding: 10, borderRadius: 8, alignItems: 'center', marginTop: 15 },
  btnCloseStrong: { backgroundColor: COLORS.bgButtonAlt, padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 10 },
  btnCloseText: { color: COLORS.text, fontWeight: 'bold' },

  cardMonetisasi: { backgroundColor: COLORS.bgSoft, padding: 15, borderRadius: 10, borderWidth: 1, borderColor: COLORS.green, marginBottom: 20 },
  progressBarBg: { height: 10, backgroundColor: COLORS.border, borderRadius: 5, marginTop: 10, overflow: 'hidden' },
  progressBarFill: { height: '100%', backgroundColor: COLORS.blue },
  persenText: { color: COLORS.textDim, fontSize: 10, textAlign: 'right' },
  btnBayar: { backgroundColor: COLORS.green, marginTop: 15, padding: 10, borderRadius: 8, alignItems: 'center' },
  btnBayarText: { color: COLORS.text, fontWeight: 'bold' },
  cardPaket: { backgroundColor: COLORS.bgInput, padding: 15, borderRadius: 8, borderWidth: 1, borderColor: COLORS.borderSoft, marginBottom: 15 },
  cardInvoice: { width: '100%', backgroundColor: COLORS.bgInput, padding: 15, borderRadius: 8, borderWidth: 1, borderColor: COLORS.blue, marginBottom: 20 },

  spacer40: { height: 40 },
  mt10: { marginTop: 10 },
  mt15: { marginTop: 15 },
  wFull: { width: '100%' },

  listFileBox: { marginBottom: 10 },
  fileItemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.bgInput,
    padding: 10,
    borderRadius: 6,
    marginBottom: 6,
  },
  fileItemText: { color: COLORS.text, flex: 1, fontSize: 12 },
  fileItemDelete: { color: COLORS.red, fontWeight: 'bold', paddingHorizontal: 8 },

  btnDanger: { backgroundColor: COLORS.red, padding: 12, borderRadius: 8, alignItems: 'center' },
  btnDangerText: { color: COLORS.text, fontWeight: 'bold' },

  listSuratBox: { maxHeight: 200 },
  listSuratItem: { backgroundColor: COLORS.bgInput, padding: 10, borderRadius: 6, marginBottom: 6, borderLeftWidth: 3 },
  listSuratItemAcc: { borderLeftColor: COLORS.green },
  listSuratItemPending: { borderLeftColor: COLORS.blue },
  listSuratHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  listSuratNomor: { color: COLORS.blue, fontWeight: 'bold', fontSize: 11 },
  listSuratTanggal: { color: COLORS.textDim, fontSize: 10 },
  listSuratPerihal: { color: COLORS.text, fontSize: 12, marginTop: 3 },
  listSuratStatusAcc: { color: COLORS.green, fontSize: 10, marginTop: 2, fontWeight: 'bold' },
  listSuratStatusPending: { color: COLORS.yellow, fontSize: 10, marginTop: 2, fontWeight: 'bold' },
  dividerTop: { marginTop: 15, borderTopWidth: 1, borderTopColor: COLORS.border, paddingTop: 12 },

  cardSubscription: { backgroundColor: COLORS.bgInput, padding: 12, borderRadius: 8, marginBottom: 12, borderLeftWidth: 3, borderLeftColor: COLORS.textHint },
  cardSubscriptionAktif: { borderLeftColor: COLORS.green },
  cardPerDoc: { backgroundColor: COLORS.bgInput, padding: 12, borderRadius: 8, borderLeftWidth: 3, borderLeftColor: COLORS.blue },
  cardPerDocDim: { borderLeftColor: COLORS.textHint, opacity: 0.6 },

  badgeMiniGreen: { backgroundColor: COLORS.green, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  badgeMiniGray: { backgroundColor: COLORS.bgButtonAlt, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  badgeMiniBlue: { backgroundColor: COLORS.blue, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  badgeMiniRed: { backgroundColor: COLORS.red, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  badgeMiniText: { color: COLORS.text, fontSize: 10, fontWeight: 'bold' },

  titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  titleCardText: { color: COLORS.text, fontWeight: 'bold', fontSize: 13 },
  subtitleCardText: { color: COLORS.textDim, fontSize: 11, marginBottom: 12 },
  textSmall: { color: COLORS.text, fontSize: 12 },
  textSmallMuted: { color: COLORS.textHint, fontSize: 12, fontStyle: 'italic' },
  textAccentGreen: { color: COLORS.green, fontWeight: 'bold' },
  textAccentYellow: { color: COLORS.yellow, fontWeight: 'bold' },
  textAccentBlue: { color: COLORS.blue, fontWeight: 'bold' },
  textUnlimited: { color: COLORS.green, fontSize: 12, marginTop: 5, fontWeight: 'bold' },
  textNoteGreen: { color: COLORS.green, fontSize: 11, marginTop: 6, fontStyle: 'italic' },
  textCenter: { textAlign: 'center' },
  textCenterMuted: { color: COLORS.textDim, fontSize: 11, textAlign: 'center', marginBottom: 15 },

  btnSubscription: { backgroundColor: COLORS.primary, padding: 10, borderRadius: 6, alignItems: 'center', marginTop: 10 },
  btnSubscriptionText: { color: COLORS.text, fontWeight: 'bold', fontSize: 12 },
  btnGreenSmall: { backgroundColor: COLORS.green, padding: 10, borderRadius: 6, alignItems: 'center', marginTop: 10 },
  btnGreenSmallText: { color: COLORS.text, fontWeight: 'bold', fontSize: 12 },

  scrollMax: { maxHeight: 320 },
  fileListItem: { backgroundColor: COLORS.bgInput, padding: 12, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: COLORS.blue },
  fileListText: { color: COLORS.text, fontSize: 13 },
  btnFullGreen: { backgroundColor: COLORS.green, padding: 14, borderRadius: 8, alignItems: 'center' },
  btnFullGreenText: { color: COLORS.text, fontWeight: 'bold', fontSize: 14 },
  btnFullWidth: { width: '100%' },
  qrWrapper: { padding: 10, backgroundColor: COLORS.white, borderRadius: 10, marginBottom: 15 },
  simNote: { color: COLORS.yellow, fontSize: 10, fontStyle: 'italic' },
  center: { alignItems: 'center' },
});

export const loginStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg, justifyContent: 'center', alignItems: 'center', padding: 20 },
  title: { color: COLORS.text, fontSize: 28, fontWeight: 'bold', marginBottom: 5 },
  subtitle: { color: COLORS.green, fontSize: 14, marginBottom: 30 },
  formBox: { width: '100%', backgroundColor: COLORS.bgSoft, padding: 20, borderRadius: 10, borderWidth: 1, borderColor: COLORS.border },
  label: { color: COLORS.text, marginBottom: 5, fontSize: 12 },
  input: { backgroundColor: COLORS.bgInput, color: COLORS.text, height: 50, borderRadius: 8, paddingHorizontal: 15, marginBottom: 20 },
  button: { backgroundColor: COLORS.primary, height: 50, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  buttonText: { color: COLORS.text, fontWeight: 'bold', fontSize: 16 },
});